// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1AStS9CBLWdTl92iuXT7h2CsRmA41Ug',
    appId: '1:263598081652:web:251de9ec056fe595a03321',
    messagingSenderId: '263598081652',
    projectId: 'iiitk-events',
    authDomain: 'iiitk-events.firebaseapp.com',
    storageBucket: 'iiitk-events.firebasestorage.app',
    measurementId: 'G-H32PH7VHKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwagmfubCLTC8lKxoP5_HhTJ5udBKz81w',
    appId: '1:263598081652:android:52dcf0d0a318134aa03321',
    messagingSenderId: '263598081652',
    projectId: 'iiitk-events',
    storageBucket: 'iiitk-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5GNxVEN5pzVQygoO-VnfkM7i3BjXc3k8',
    appId: '1:263598081652:ios:56c2a97ce45bbcd7a03321',
    messagingSenderId: '263598081652',
    projectId: 'iiitk-events',
    storageBucket: 'iiitk-events.firebasestorage.app',
    iosBundleId: 'com.example.iiitkEvents',
  );
}
